site_name: Лабораторная работа 1 - Документация по программированию с сокетами
docs_dir: docs
site_description: >
  Документация для Лабораторной работы 1, охватывающая клиент-серверное взаимодействие,
  многопользовательский чат и реализацию веб-сервера с использованием сокетов Python.

nav:
  - Главная: index.md
  - Лабораторная работа 1:
      - "Задание 1: Клиент-серверное взаимодействие с использованием UDP": Lr1/task1.md
      - "Задание 2: Математические операции через TCP": Lr1/task2.md
      - "Задание 3: HTTP-сервер, возвращающий HTML-страницу": Lr1/task3.md
      - "Задание 4: Многопользовательский чат на сокетах": Lr1/task4.md
      - "Задание 5: Веб-сервер для обработки GET и POST запросов": Lr1/task5.md
      - "LeetCode: Задачи": Lr1/leetcode.md
  - Лабораторная работа 2:
      - "Задание": Lr2/task1_2.md
